spring.application.name=allgenda
spring.datasource.url=jdbc:postgresql://localhost:5432/allgenda
spring.datasource.username=allgenda_user
spring.datasource.password=alljgc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
